name: Dependabot Auto-Merge

on:
  pull_request:
    branches: ["master", "main"]
    types: [opened, synchronize, reopened]

# Define permissions at the workflow level
permissions:
  pull-requests: write # Needed to merge PRs and comment
  contents: write # Needed to update the repository (e.g., merge commits)

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' # Only trigger for Dependabot PRs
    steps:
      - name: Auto-merge Dependabot PRs
        run: |
          gh pr comment "$PR_URL" --body "Auto-merging this Dependabot PR."
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
